// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DamageSystemDamageEventHandler {
        
        private test.DamageEvent _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private int ActionNode4_a = default( System.Int32 );
        
        private int ActionNode4_b = default( System.Int32 );
        
        private int ActionNode4_Result = default( System.Int32 );
        
        private object ActionNode8_a = default( System.Object );
        
        private object ActionNode8_b = default( System.Object );
        
        private int IntNode9 = 0;
        
        private bool ActionNode8_Result = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode10_gameObject = default( UnityEngine.GameObject );
        
        private int ActionNode11_in = default( System.Int32 );
        
        private float ActionNode11_Result = default( System.Single );
        
        private float ActionNode10_time = default( System.Single );
        
        public test.DamageEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode4_a = Event.damaged.health;
            ActionNode4_b = Event.amount;
            // ActionNode
            // Visit uFrame.ECS.Actions.IntLibrary.Subtract
            ActionNode4_Result = uFrame.ECS.Actions.IntLibrary.Subtract(ActionNode4_a, ActionNode4_b);
            ActionNode8_a = ActionNode4_Result;
            ActionNode8_b = IntNode9;
            // ActionNode
            // Visit uFrame.ECS.Actions.Comparisons.AreEqual
            ActionNode8_Result = uFrame.ECS.Actions.Comparisons.AreEqual(ActionNode8_a, ActionNode8_b, ActionNode8_yes, ActionNode8_no);
        }
        
        private void ActionNode8_yes() {
            ActionNode10_gameObject = Event.damaged.gameObject;
            ActionNode11_in = IntNode9;
            // ActionNode
            // Visit uFrame.ECS.Actions.Converter.IntToFloat
            ActionNode11_Result = uFrame.ECS.Actions.Converter.IntToFloat(ActionNode11_in);
            ActionNode10_time = ActionNode11_Result;
            // ActionNode
            // Visit uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject
            uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject(ActionNode10_gameObject, ActionNode10_time);
        }
        
        private void ActionNode8_no() {
            // SetVariableNode
            Event.damaged.health = (System.Int32)ActionNode4_Result;
        }
    }
}
