// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class InputSystemUpdateHandler {
        
        private uFrame.ECS.APIs.ISystemUpdate _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private string ActionNode30_name = default( System.String );
        
        private string StringNode33 = "space";
        
        private bool ActionNode30_Result = default( System.Boolean );
        
        private bool ActionNode15_value = default( System.Boolean );
        
        private test.MenuToggleEvent PublishEventNode16_Result = default( test.MenuToggleEvent );
        
        public uFrame.ECS.APIs.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode30_name = StringNode33;
            // ActionNode
            // Visit UnityEngine.Input.GetKeyDown
            ActionNode30_Result = UnityEngine.Input.GetKeyDown(ActionNode30_name);
            ActionNode15_value = ActionNode30_Result;
            // ActionNode
            // Visit uFrame.ECS.Actions.Comparisons.IsTrue
            uFrame.ECS.Actions.Comparisons.IsTrue(ActionNode15_value, ActionNode15_yes, ActionNode15_no);
        }
        
        private void ActionNode15_yes() {
            // PublishEventNode
            var PublishEventNode16_Event = new MenuToggleEvent();
            System.Publish(PublishEventNode16_Event);
            PublishEventNode16_Result = PublishEventNode16_Event;
        }
        
        private void ActionNode15_no() {
        }
    }
}
