// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class InputSystemOnMouseDownHandler {
        
        public Health Source;
        
        private uFrame.ECS.UnityUtilities.MouseDownDispatcher _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private int IntNode7 = 5;
        
        private test.DamageEvent PublishEventNode6_Result = default( test.DamageEvent );
        
        public uFrame.ECS.UnityUtilities.MouseDownDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // PublishEventNode
            var PublishEventNode6_Event = new DamageEvent();
            PublishEventNode6_Event.amount = IntNode7;
            PublishEventNode6_Event.damaged = this.Source;
            System.Publish(PublishEventNode6_Event);
            PublishEventNode6_Result = PublishEventNode6_Event;
        }
    }
}
