// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemMenuToggleEventHandler {
        
        public MenuComponent Group;
        
        private test.MenuToggleEvent _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private bool ActionNode18_value = default( System.Boolean );
        
        private bool BoolNode20 = false;
        
        private bool BoolNode22 = true;
        
        public test.MenuToggleEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode18_value = Group.gameObject.active;
            // ActionNode
            // Visit uFrame.ECS.Actions.Comparisons.IsTrue
            uFrame.ECS.Actions.Comparisons.IsTrue(ActionNode18_value, ActionNode18_yes, ActionNode18_no);
        }
        
        private void ActionNode18_yes() {
            // SetVariableNode
            Group.gameObject.active = (System.Boolean)BoolNode20;
        }
        
        private void ActionNode18_no() {
            // SetVariableNode
            Group.gameObject.active = (System.Boolean)BoolNode22;
        }
    }
}
