// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class DamageSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<MenuComponent> _MenuComponentManager;
        
        private IEcsComponentManagerOf<Health> _HealthManager;
        
        private DamageSystemDamageEventHandler DamageSystemDamageEventHandlerInstance = new DamageSystemDamageEventHandler();
        
        public IEcsComponentManagerOf<MenuComponent> MenuComponentManager {
            get {
                return _MenuComponentManager;
            }
            set {
                _MenuComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Health> HealthManager {
            get {
                return _HealthManager;
            }
            set {
                _HealthManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            MenuComponentManager = ComponentSystem.RegisterComponent<MenuComponent>(3);
            HealthManager = ComponentSystem.RegisterComponent<Health>(1);
            this.OnEvent<test.DamageEvent>().Subscribe(_=>{ DamageSystemDamageEventFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void DamageSystemDamageEventHandler(test.DamageEvent data) {
            var handler = DamageSystemDamageEventHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void DamageSystemDamageEventFilter(test.DamageEvent data) {
            this.DamageSystemDamageEventHandler(data);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("01516cc7-34dc-40a6-a748-432bf37cb050")]
    public partial class DamageSystem : DamageSystemBase {
        
        private static DamageSystem _Instance;
        
        public DamageSystem() {
            Instance = this;
        }
        
        public static DamageSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
