// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class levelSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<TestComponentNode> _TestComponentNodeManager;
        
        public IEcsComponentManagerOf<TestComponentNode> TestComponentNodeManager {
            get {
                return _TestComponentNodeManager;
            }
            set {
                _TestComponentNodeManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            TestComponentNodeManager = ComponentSystem.RegisterComponent<TestComponentNode>(1);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("1cb84ce4-3032-4b6f-9b06-4dd493ada89d")]
    public partial class levelSystem : levelSystemBase {
        
        private static levelSystem _Instance;
        
        public levelSystem() {
            Instance = this;
        }
        
        public static levelSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
