// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(1)]
    [uFrame.Attributes.uFrameIdentifier("3cf05187-6e63-4e34-8442-dd3d3740e2a7")]
    public partial class TestComponentNode : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _NochEinTEst;
        
        [UnityEngine.SerializeField()]
        private string[] _Collections;
        
        private ReactiveCollection<System.String> _CollectionsReactive;
        
        private Subject<PropertyChangedEvent<Int32>> _NochEinTEstObservable;
        
        private PropertyChangedEvent<Int32> _NochEinTEstEvent;
        
        public override int ComponentId {
            get {
                return 1;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> NochEinTEstObservable {
            get {
                return _NochEinTEstObservable ?? (_NochEinTEstObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 NochEinTEst {
            get {
                return _NochEinTEst;
            }
            set {
                SetNochEinTEst(value);
            }
        }
        
        public ReactiveCollection<System.String> Collections {
            get {
                if (_CollectionsReactive == null) {
                    _CollectionsReactive = new ReactiveCollection<System.String>(_Collections ?? new System.String[] { });
                }
                return _CollectionsReactive;
            }
        }
        
        public virtual void SetNochEinTEst(Int32 value) {
            SetProperty(ref _NochEinTEst, value, ref _NochEinTEstEvent, _NochEinTEstObservable);
        }
    }
}
