// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS;
    using UniRx;
    
    
    [uFrame.Attributes.EventId(1)]
    public partial class DamageEvent : object {
        
        [UnityEngine.SerializeField()]
        private Int32 _amount;
        
        [UnityEngine.SerializeField()]
        private Health _damaged;
        
        public Int32 amount {
            get {
                return _amount;
            }
            set {
                _amount = value;
            }
        }
        
        public Health damaged {
            get {
                return _damaged;
            }
            set {
                _damaged = value;
            }
        }
    }
}
