// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [UnityEditor.InitializeOnLoadAttribute()]
    [uFrame.Attributes.uFrameIdentifier("8b4747f3-c9fd-4f81-88f2-79b4140a8af8")]
    public class testEditorExtensions {
        
        [UnityEditor.MenuItem("GameObject/Create test Kernel", false, 0)]
        public static void AddKernel() {
            uFrame.ECS.Templates.EcsEditorExtensionTemplate.AddEcsKernelWith<test.testLoader>();
        }
    }
}
